apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080