apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
      nodePort: 30080
  type: LoadBalancer 